Covenants: touch up covenant id parsing
We can simply make `INVALID` our default value for the numeric id
instead of playing games with `-1`.

Fixes compile error on vs1019:
  error C4146: unary minus operator applied to unsigned type, result still unsigned